### ISSUE TITLE
openssl 1.0.1 handshake failure

### ISSUE THREAD

**Issue by sureL89** [EUDAT-B2SAFE/B2HANDLE#106]
Hi, 
I am using openssl 1.0.1 under debian8 and I receive a handshake error when I try to execute generate_and_register_handle. Retrieving a handle record works without any problems. I try this with an unencrypted private key.

Here is the handle server log output:
2016-10-27 14:01:17.649:WARN:oeji.nio:javax.net.ssl.SSLHandshakeException: General SSLEngine problem

The B2HANDLE Exception:
SSLError: [SSL: SSL_HANDSHAKE_FAILURE] ssl handshake failure (_ssl.c:1750)

**Comment by cookie33** [comment]
HI,

Have you looked at the common problems: http://eudat-b2safe.github.io/B2HANDLE/authentication.html#common-problems

To make sure it is not a configuration error, could you try to do the same action with curl? f.i.
```
curl --key ./my_privkey.pem --cert ./my_certificate_only.pem  -H "Content-Type:application/json" -H 'Authorization: Handle clientCert="true"' -X PUT --data '{"values":[{"index":100,"type":"HS_ADMIN","data":{"value":{"index":200,"handle":"0.NA\/<my_prefix>","permissions":"011111110011","format":"admin"},"format":"admin"}},{"index":1,"type":"URL","data":"http://www.google.com"}]}' https://<my_handle_server>:<my_handle_port>/api/handles/<my_prefix>/my_test_handle
```

* my_privkey.pem = is the private key converted to pem format
* my_certificate_only.pem = is the private key and user to authenticate against. Only the certificate, remove pubkey.
* replace the following: <my_prefix> , <my_handle_server> and <my_handle_port> with the appropriate values.

**Comment by sureL89** [comment]
Hi,
thank you so much. curl helped me to track down the problem. I had to uncomment
#req_extensions = v3_req # The extensions to add to a certificate request
in openssl.cnf before creating the client certificate

Problem solved, and handle server ready to go.

**Comment by cookie33** [comment]
Hi,

@ sureL89. Thanks for the feedback. How did you notice using curl? This might be handy in the documents/issues.

@ B2HANDLE
Is this one to add to the documentation? Mention that it might be a problem.

The user might have a openssl.conf where it mentions `req_extensions = v3_req`. The section `v3_req` (in openssl.conf) might than have incompatible parameters.

**Comment by TobiasWeigel** [comment]
I'm fine with putting this in the documentation, however, I am not sure I understand everything correctly. Was the problem caused by extensions (via the switch you mentioned) being included in the certificate request or was it caused by those extensions missing?

**Comment by sureL89** [comment]
@TobiasWeigel @cookie33 
After redoing the whole process the req_extension was not the problem.
There was a typo in the CN during the client certificate creation.
Blame on me. 
Sorry for the wrong alarm but your curl tip with verbose mode was a great possibility for rechecking the ssl handshake.

Sorry guys, keep up the good work and thank you for the fast response.
