### ISSUE TITLE
Docs: search not working / outdated Sphinx

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2SAFE/B2HANDLE#126]
Problem: The search within the github.io docs is not working. The reason is probably an outdated/mismatched jquery package within the deployment. A rebuild with the latest sphinx version should fix the issue; this will be done as part of the next release process where the Jenkins build jobs will run.

**Comment by NicolasLiampotis** [comment]
See PR #127

**Comment by themiszamani** [comment]
Search Functionality is working properly now. Documentation and theme  updated. 
Here is the latest one https://eudat-b2safe.github.io/B2HANDLE/
