### ISSUE TITLE
http://eudat-b2safe.github.io/B2HANDLE/authentication.html#using-client-certificates

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE#60]
The 3d method described is as follows:

By adding the usernames (300:foo/bar and 301:foo/bar) to any HS_VLIST entry referenced somewhere in 0.NA/foo. For example, if there is a HS_ADMIN at index 101 of 0.NA/foo which points to a HS_VLIST at the index 200 in 0.NA/foo, which points to a HS_VLIST at index 200 in `foo/admin`, which points to a HS_SECKEY at index 300 in ‘foo/bar’ - then 300:foo/bar is a username with all the permissions stated in the HS_ADMIN entry at the index 101 of 0.NA/foo.

Suddenly `foo/admin` is mentioned. And the example shown also talks about `foo/bar`. There seems to be a miscommunication here.

We might even add a fourth method. Which is a derivate of the 3th method. This makes sure the `0.NA/foo` has to be updated only once. But gives even more flexibility:

For example, if there is a HS_ADMIN at index 101 of 0.NA/foo which points to a HS_VLIST at the index 200 in 0.NA/foo, which points to a HS_VLIST at index 200 in `foo/admin`, which points to several HS_VLIST at index 200 in for instance `foo/user01`, `foo/user02`. For each there is a HS_VLIST which points to a HS_SECKEY at index 300 in ‘foo/user01’ - then 300:foo/user1 is a username with all the permissions stated in the HS_ADMIN entry at the index 101 of 0.NA/foo.

    **Handle record 0.NA/foo:**

    ===== ========= =======================
    Index Key       Value
     ...  ...       ...
    100   HS_ADMIN  (refers to 200:0.NA/foo)
    200   HS_VLIST  200:foo/admin
     ...  ...       ...
    ===== ========= =======================

    **Handle record foo/admin:**

    ===== ========= =======================
    Index Key       Value
     ...  ...       ...
    200   HS_VLIST  200:foo/user01
                    200:foo/user02
     ...  ...       ...
    ===== ========= =======================

    **Handle record foo/user01:**

    ===== ========= =======================
    Index Key       Value
     ...  ...       ...
    200   HS_VLIST  300:foo/user01
                    301:foo/user01
    300   HS_SECKEY *mypassworduser1*
    301   HS_PUBKEY 0000A552100
     ...  ...       ...
    ===== ========= =======================

    **Handle record foo/user02:**

    ===== ========= =======================
    Index Key       Value
     ...  ...       ...
    200   HS_VLIST  300:foo/user02
                    301:foo/user02
    300   HS_SECKEY *mypassworduser2*
    301   HS_PUBKEY 0000A552200
     ...  ...       ...
    ===== ========= =======================

This way a project can get it's own username. They either can use the default `200:0.NA/foo` as the handle owner when generating handles or use `200:foo/user0{1,2}` as the handle owner. This makes sure only the handle owner can change handles.

**Comment by TobiasWeigel** [comment]
This looks like a documentation issue to me that has not been addressed in one of today's PRs. If you want it included in the v1.0.1 release, please create a PR, otherwise I will proceed with the release. I think it is safe to update the docs also after the release.

**Comment by cookie33** [comment]
I think the documentation can be updated later for this.
Go ahead with the release.

**Comment by merretbuurman** [comment]
Hi,
I've updated the documentation and created #PR 67. I guess this can be included in the next release 1.0.2.

**Comment by merretbuurman** [comment]
PR #67 merged. Will be included in 1.0.2.
