### ISSUE TITLE
open-ssl0.98 Handshake error

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SAFE/B2HANDLE#64]
When using open-ssl0.98 you will receive a handshake error when authenticating. Problem is solved when using openssl 1.0.1 or higher. 
In the current documentation there is nor remark on which open-ssl version should be used. Maybe it is good to set directly on the front page as a dependency.

**Comment by merretbuurman** [comment]
Solved in PR 71, will be included in 1.0.2.
