### ISSUE TITLE
SSLError: SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SAFE/B2HANDLE#65]
This error occurs when the server certificate is not in the trusted CA's of the client.
Solution 1) Add the certificate to the trusted CA's
Solution 2) Set "HTTPS_verify": "False"

Can this be added to the documentation Section "Using client certificates"?

**Comment by javaguirre** [comment]
You could also pass [now a valid CA](https://github.com/EUDAT-B2SAFE/B2HANDLE/issues/55). :-)

**Comment by merretbuurman** [comment]
There should be a way to avoid solution 2, of course. @cookie33 : Was this fixed with PR #70 ?

**Comment by cookie33** [comment]
Nope. This is fixed by either:
* adding CA certificate to system bundle
* adding path of CA certificate to HTTPS_verify
* set "HTTPS_verify": "False"

Described in documentation fix to be committed

**Comment by merretbuurman** [comment]
Adapted in PR #71. Will be included in 1.0.2.
