### ISSUE TITLE
Documentation: 5 Optional: Removing the public key from the certificate file:

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE#66]
In the Documentation "Using client certificates" it states that step 5: "Optional: Removing the public key from the certificate file:" is optional. It is NOT really optional. It works best with a separate private key in pem format and a separate client certificate without public key.

So please remove the "Optional" statement and make it part of the normal workflow.

**Comment by merretbuurman** [comment]
Adapted in PR #71. Will be included in release 1.0.2.
