### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by momipsl** [EUDAT-B2SAFE/B2HANDLE#81]
We are writing a [dataset errata service](https://github.com/ES-DOC/esdoc-errata-ws) that needs to integrate with a handler service instance.  It would be useful to be able to pip install this library.

**Comment by merretbuurman** [comment]
Making the library available on PyPi is planned for the near future, so I'm leaving the issue open until that's done.

**Comment by emanueldima** [comment]
We also would need this in B2SHARE

**Comment by emanueldima** [comment]
@merretbuurman @TobiasWeigel Any chance for this issue be solved in a 2 or 3 days?

**Comment by TobiasWeigel** [comment]
Hello Emanuel,
we can publish the current version on PyPI - but do you actually need a Python 2 version?
The refactoring to pyhandle is planned for September - you may have to change your imports then again.
Best, Tobias

**Comment by emanueldima** [comment]
No, you're right, we need a python 3 version, so we will wait. Thanks!

**Comment by TobiasWeigel** [comment]
I have now added b2handle 1.0.3 to PyPI:
https://pypi.python.org/pypi?name=b2handle&version=1.0.3&:action=display

There is an remaining issue with the PyPI info page, however; the README file format is in markdown (for GitHub), but PyPI needs it in restructured text. The automatic conversion currently garbles the build badge images. Manually editing the PyPI page does not seem possible, so we have to fix this in the next release.
