### ISSUE TITLE
order

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2HANDLE#89]
On the page: http://eudat-b2safe.github.io/B2HANDLE/creatingclientcertificates.html#creatingclientcertificate

it states "Creating the certificate file":

And than it has:
- This can be done using openssl without specifying a subject:
- This can be done using openssl with specifying a subject:
- The tool is then going to prompt for some information if you don not specify a subject. 

Would it better if it states:
This can be done in 2 ways:
Case#1
- Creating the certificate can be done using openssl with specifying a subject:

Done

Case#2 
- Creating the certificate can be done using openssl without specifying a subject:
- The tool is then going to prompt for some information if you don not specify a subject. 

Done

It also states "don not" and "do not" is a little better english.

**Comment by TobiasWeigel** [comment]
This has been addressed in PR #107
